### ISSUE TITLE
Support npm_config_build_from_source in place of SKIP_SWC_BINARY_DOWNLOAD_FOR_CI

### ISSUE THREAD

**Issue by kapouer** [swc-project/node-swc#12]
Hi,

amongst several node addons that need to be compiled, it is quite common to support
`npm install --build-from-source`, which environment-variable-wise, translates to
`npm_config_build_from_source=true`.
(node-pre-gyp and all reverse build-dependencies of it support it, and even some others).

**Comment by kdy1** [comment]
@kapouer Is `npm_config_build_from_source` a environment variable?

**Comment by kdy1** [comment]
I'll close this after checking that --build-from-source is working

**Comment by kapouer** [comment]
Yes, it is. npm consolidates all parameters into env variables.
I can confirm it works (as i just tried it):
```
npm install --build-from-source swc-project/node-swc

> @swc/core@1.1.1 install /home/dev/Software/github/postinstall-js/node_modules/@swc/core
> node scripts/install.js || neon build --release

Building swc from source code
```
Thank you !
