### ISSUE TITLE
Builds for darwin-x64-79?

### ISSUE THREAD

**Issue by james2doyle** [swc-project/node-swc#14]
<img width="1002" alt="Screen Shot 2019-12-03 at 7 10 17 PM" src="https://user-images.githubusercontent.com/1425304/70109391-968f3480-1600-11ea-96d4-92dcbf0c8c91.png">

Looks like some of the latest OSX binaries are missing?

**Comment by kdy1** [comment]
@james2doyle Published v1.1.3, which contains prebuilt binary for nodejs@13

**Comment by james2doyle** [comment]
Perfect! Thanks
