### ISSUE TITLE
`i686-pc-windows-msvc` target may not be installed

### ISSUE THREAD

**Issue by anurbol** [swc-project/node-swc#16]
I don't really know if I am doing something very naive or not but I am trying to build node-swc 
by running `neon-cli build --release` and I got this error.

```

Compiling ppv-lite86 v0.2.
Compiling rand_core v0.4.2
  error[E0463]: can't find crate for `std`
  |
  = note: the `i686-pc-windows-msvc` target may not be installed

```

Why does it tries to install something related to `i686` when I am on 64 bit Windows 10?

**Comment by kdy1** [comment]
neon cli should be invoked like
neon build --release

and if you are doing so, it seems like a bug of neon

**Comment by anurbol** [comment]
I moved to Wasm. This issue is not important for me now.
