### ISSUE TITLE
Smaller binary size

### ISSUE THREAD

**Issue by simnalamburt** [swc-project/node-swc#17]
On AMD64 Linux with Rust 1.42.0-nightly+6d3f4e0aa, the size of libffi.so is 25279568B = 26.23MiB, which is rather big. There're 2 options that we can do without tradeoffs, and 1 option that we can choose between tradeoff.

1. Enable LTO: 26.23MiB → 24.11MiB, -8%\
\
I just found that LTO was disabled on purpose at commit https://github.com/swc-project/node-swc/commit/ffde24e0. Was there any reason?

2. Strip the binary: 26.23MiB → 20.89MiB, -20%\
\
simple `strip -s libffi.so` is enough.

3. Use Trait Object and vtable instead of generic instantiation and monomorphism for **a few big functions**.\
\
We don't need to avoid monomorphism at all. Just disabling it for a few big functions will suffice. For example, single "swc_ecma_ast::expr::fold_children" takes 1.225MiB which is 5% of binary.\
\
Using Trait Object will introduce a small runtime overhead. We need to measure the amount of overhead so that we can choose wisely between tradeoffs.

See [summary.gz](https://github.com/swc-project/node-swc/files/4114317/summary.gz) for summary of cargo-bloat result.
See [cargo-bloat.json.gz](https://github.com/swc-project/node-swc/files/4114297/cargo-bloat.json.gz) for full cargo-bloat result.

<details><summary>A code that I used to generate 'summary.gz'</summary>
<pre><code>#!/usr/bin/env python3
import json, collections
data = json.load(open('cargo-bloat.json'))
accum = collections.defaultdict(int)
for entry in data['functions']:
    accum[entry['name']] += entry['size']
for fn, size in sorted(accum.items(), key=lambda e:e[1], reverse=True):
    print(f'{size:10}\t{fn}')
</code></pre>
</details>

**Comment by simnalamburt** [comment]
```python
YO
```

**Comment by kdy1** [comment]
@simnalamburt I disabled it because it timeouts on osx. Strip seems great. Is it ok to strip .node file?

For 3, I think using trait objects would make swc faster due to cpu cache issue. I'll investigate on it.

**Comment by kdy1** [comment]
Btw, how did you get cargo bloat result?

**Comment by simnalamburt** [comment]
I ran https://github.com/RazrFalcon/cargo-bloat like this

```
cargo bloat --release -n 0 --no-relative-size -w --message-format json
```

**Comment by kdy1** [comment]
I did 1 and 2. As 3 should be done at swc-project/swc, I'm closing this.
