### ISSUE TITLE
transformSync with an AST does not transform

### ISSUE THREAD

**Issue by devongovett** [swc-project/node-swc#22]
The following seems to only re-print the AST rather than actually transform. Passing the code directly works fine, but in cases where I need to do something with the AST prior to transforming, it would be nice to avoid reparsing.

```js
swc.transformSync(swc.parseSync(code), {module: {type: 'commonjs'}})
````

Should [this](https://github.com/swc-project/node-swc/blob/3fe7c16797c458b162a9039f4af220e767a4bf8e/native/src/lib.rs#L188) call `process_js` instead of `print_js`?

**Comment by kdy1** [comment]
Oh.. you are right.

**Comment by devongovett** [comment]
Whoa. You are fast! 😄 

This one looks similar for the async version btw: https://github.com/swc-project/node-swc/blob/3fe7c16797c458b162a9039f4af220e767a4bf8e/native/src/lib.rs#L100

**Comment by kdy1** [comment]
@devongovett Thank you very much!

**Comment by kdy1** [comment]
I'll publish a new version after fixing https://github.com/swc-project/swc/issues/675

**Comment by devongovett** [comment]
Thanks for releasing! I'm running into a new error now that I've passed the pre-parsed AST to `transformSync`:

```
internal error in Neon module: cannot access a scoped thread local variable without calling `set` first
```

A small test case using [this file](https://github.com/mrdoob/three.js/blob/dev/src/Three.Legacy.js):

```js
let contents = fs.readFileSync('Three.Legacy.js', 'utf8');
swc.transformSync(swc.parseSync(contents), {module: {type: 'commonjs'}})
```


However, when just passing the code directly it works:

```js
swc.transformSync(contents, {module: {type: 'commonjs'}})
```

Happy to open a separate issue if you want.

**Comment by kdy1** [comment]
@devongovett Thanks for reporrting a bug! I'll fix this soon. I'll add some patches to https://github.com/swc-project/swc/pull/683, and release a new version today.

**Comment by kdy1** [comment]
@devongovett  I fixed it and published a new version
